### ISSUE TITLE
Import "gravityai" could not be resolved

### ISSUE THREAD

**Issue by ong-yy** [GravityAI/gravityai#5]
Hi, I followed the example and tried importing gravityai but it gives the error
`Import "gravityai" could not be resolved`

I installed gravityai with the following commands 
```
pip install gravityai

python3.9 -m pip install gravityai
```

My code as below 
```python
from gravityai import gravityai as grav
.
.
```

Please let me know what can I do to fix this?

**Comment by gravity-ai** [comment]
Sorry for the trouble, our package did not build correctly.  Please use the latest version available in Pypi (0.1.4.post2).
